config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :articles
  # get 'page/home'
  root 'articles#index'

  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    # redirect_to articles_path
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user && !current_user.admin?

    flash[:alert] = 'You can only edit or delete your own article'
    redirect_to @article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %> </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article, class: "text-success"%></h5>
            <p class="card-text"><%= truncate(article.description, length:100)%></p>
            <%= link_to "View", article, class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", data: { "turbo_confirm": 'Are you sure?', "turbo-method": :delete } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!--  <p>-->
  <%#= link_to "New article", new_article_path %>
  <!--  </p>-->
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with(model: article, class: "shadow p-3 mb-3 bg-info rounded") do |form| %>
       <div class="row justify-content-center">
      <div class= "col-10">
        <%= render 'shared/errors', obj:article %>
        <div class="form-group row">
          <%= form.label :title, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.text_field :title,rows:10, class: "form-control"%>
          </div>
        </div>
        <br>
        <div class="form-group row justify-content-center">
          <%= form.label :description, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.text_area :description,rows:10, class: "form-control"%>
          </div>
        </div>
        <br>
        <div class="form-group row justify-content-center">
          <%= form.label :category, style: "display: block", class: "col-2 col-form-label"%>
          <div class="col-10">
            <%= form.collection_select :category_ids, Category.all, :id, :name,
                                       { prompt: 'Make your selection from the list below (can be empty)'},
                                       { multiple: true, size: 4, class: 'custom-select' } %>
          </div>
        </div>
        <br>
        <div class="form-group row">
          <%= form.submit class:" btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to "Back to articles", articles_path, class:"row justify-content-center"%>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"> Edit article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<!--<p style="color: green"><%#= notice %></p>-->
<h1 class="text-center mt-4"> Listing all articles</h1>

<div class="flickr_pagination text-center">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles' %>
<div class="flickr_pagination mb-4 text-center">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4"> Create new articles</h1>

<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"> <%= @article.title %>></h2>
<div class="container">

    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow-lg mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @article.user.username if @article.user %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
              <div class="mt-2"><%= render @article.categories %> </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%#= link_to "Delete", @article, class: "btn btn-outline-danger", data: { "turbo-method": :delete } %>
              <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
              edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>


  <!--  <p>-->
  <%#= link_to "New article", new_article_path %>
  <!--  </p>-->
</div>